import { STATE, NAME as NAME_COL, AGE, IMAGE_NAME } from '@shell/config/table-headers';

export const NODES_HEADER = [
  {
    ...STATE,
    name: 'status',
    value: 'stateDisplay',
    sort: ['nodeStatus.stateDisplay'],
    search: ['nodeStatus.stateDisplay'],
    width: 120,
  },
  {
    ...NAME_COL,
    width: 200,
  },
  {
    name: 'readiness',
    labelKey: 'longhorn.node.table.header.readiness',
    value: 'readiness',
    sort: ['readiness'],
    search: 'readiness',
    formatter: 'NodeReadiness',
    dashIfEmpty: true,
    width: 140,
    align: 'center',
  },
  {
    name: 'replicas',
    labelKey: 'longhorn.node.table.header.replicas',
    value: 'replicas',
    search: 'replicas',
    formatter: 'NodeReplicas',
    width: 80,
    align: 'center',
  },
  {
    name: 'allocated',
    labelKey: 'longhorn.node.table.header.allocated',
    value: 'disksAllocated',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'used',
    labelKey: 'longhorn.node.table.header.used',
    value: 'disksUsed',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'size',
    labelKey: 'longhorn.node.table.header.size',
    value: 'disksSize',
    formatter: 'DiskSize',
    width: 200,
    align: 'center',
  },
  {
    name: 'tags',
    labelKey: 'longhorn.node.table.header.tags',
    value: 'spec.tags',
    formatter: 'Tag',
  },
  AGE,
];

export const DISKS_HEADERS = [
  {
    ...STATE,
    name: 'status',
    value: 'stateDisplay',
    sort: ['diskStatus.stateDisplay'],
    search: ['diskStatus.stateDisplay'],
    width: 100,
  },
  {
    name: 'id',
    labelKey: 'longhorn.node.table.header.diskId',
    value: 'id',
    sort: ['id'],
    dashIfEmpty: true,
    width: 200,
  },
  {
    name: 'diskType',
    labelKey: 'longhorn.node.table.header.diskType',
    value: 'diskType',
    dashIfEmpty: true,
    width: 100,
  },
  {
    name: 'path',
    labelKey: 'longhorn.node.table.header.path',
    value: 'path',
    sort: ['path'],
    dashIfEmpty: true,
    width: 100,
  },
  {
    name: 'replicas',
    labelKey: 'longhorn.node.table.header.replicas',
    value: 'scheduledReplicaCounts',
    formatter: 'NodeReplicas',
    width: 80,
    align: 'center',
  },
  {
    name: 'allocated',
    labelKey: 'longhorn.node.table.header.allocated',
    value: 'diskAllocated',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'used',
    labelKey: 'longhorn.node.table.header.used',
    value: 'diskUsed',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'size',
    labelKey: 'longhorn.node.table.header.size',
    value: 'diskSize',
    formatter: 'DiskSize',
    width: 200,
    align: 'center',
  },
  {
    name: 'tags',
    labelKey: 'longhorn.node.table.header.tags',
    value: 'diskTags',
    formatter: 'Tag',
  },
  {
    name: 'healthStatus',
    labelKey: 'longhorn.node.table.header.healthStatus',
    value: 'diskHealthStatus',
    sort: ['diskHealthStatus.stateDisplay'],
    search: ['diskHealthStatus.stateDisplay'],
    formatter: 'DiskHealthStatusText',
    width: 170,
    align: 'center',
  },
];

export const VOLUMES_HEADER = [
  {
    name: 'health',
    labelKey: 'longhorn.volume.table.header.state',
    value: 'volumeStatus',
    sort: ['volumeStatus.stateDisplay'],
    search: ['volumeStatus.stateDisplay', 'dashboardStateDisplay', 'dashboardStateQueryValue:exact'],
    formatter: 'VolumeHealth',
    width: 120,
  },
  {
    name: '',
    label: '',
    value: () => '',
    formatter: 'VolumeWarnings',
    align: 'center',
  },
  {
    ...NAME_COL,
    formatter: 'VolumeNameWithIcons',
  },
  {
    name: 'size',
    labelKey: 'longhorn.volume.table.header.size',
    value: '$.spec.size',
    sort: ['$.spec.size'],
    formatter: 'Si',
    align: 'center',
    width: 100,
  },
  {
    name: 'actualSize',
    labelKey: 'longhorn.volume.table.header.actualSize',
    value: '$.status.actualSize',
    sort: ['$.status.actualSize'],
    formatter: 'Si',
    align: 'center',
    width: 100,
  },
  {
    name: 'dataEngine',
    labelKey: 'longhorn.volume.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    formatter: 'VolumeDataEngine',
    align: 'center',
    width: 120,
  },
  {
    name: 'pvPvc',
    labelKey: 'longhorn.volume.table.header.pvPvc',
    value: 'kubernetesStatus',
    formatter: 'VolumePvPvc',
    align: 'center',
    width: 100,
  },
  {
    name: 'namespace',
    labelKey: 'tableHeaders.namespace',
    value: 'kubernetesStatus.namespace',
    sort: ['kubernetesStatus.namespace'],
    dashIfEmpty: true,
    align: 'center',
    width: 100,
  },
  {
    name: 'node',
    labelKey: 'longhorn.volume.table.header.node',
    value: 'kubernetesStatus',
    search: ['replicaNodeIds', 'spec.nodeId:exact', 'spec.nodeID:exact', 'status.currentNodeID:exact'],
    formatter: 'VolumeNode',
  },
  {
    name: 'lastBackupAt',
    labelKey: 'longhorn.volume.table.header.lastBackupAt',
    value: '$.status.lastBackupAt',
    sort: ['$.status.lastBackupAt'],
    formatter: 'LiveDate',
    width: 100,
  },
  AGE,
];

export const RECURRING_JOBS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'task',
    labelKey: 'longhorn.recurringJob.table.header.task',
    value: 'taskDisplay',
    sort: ['spec.task'],
    search: ['spec.task', 'taskDisplay'],
    dashIfEmpty: true,
  },
  {
    name: 'cron',
    labelKey: 'longhorn.recurringJob.table.header.schedule',
    value: '$.spec.cron',
    sort: ['spec.cron'],
    search: ['spec.cron'],
    formatter: 'CronSchedule',
    dashIfEmpty: true,
  },
  {
    name: 'retain',
    labelKey: 'longhorn.recurringJob.table.header.retain',
    value: '$.spec.retain',
    sort: ['$.spec.retain'],
    search: '$.spec.retain',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'concurrency',
    labelKey: 'longhorn.recurringJob.table.header.concurrency',
    value: '$.spec.concurrency',
    sort: ['$.spec.concurrency'],
    search: '$.spec.concurrency',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'parameters',
    labelKey: 'longhorn.recurringJob.table.header.parameters',
    value: 'parametersDisplay',
    sort: ['spec.parameters'],
    search: ['spec.parameters', 'parametersDisplay'],
    dashIfEmpty: true,
  },
  {
    name: 'groups',
    labelKey: 'longhorn.recurringJob.table.header.groups',
    value: 'groupsDisplay',
    sort: ['spec.groups'],
    search: ['spec.groups', 'groupsDisplay'],
    dashIfEmpty: true,
  },
  {
    name: 'labels',
    labelKey: 'longhorn.recurringJob.table.header.labels',
    value: 'labelsDisplay',
    sort: ['spec.labels'],
    search: ['spec.labels', 'labelsDisplay'],
    dashIfEmpty: true,
  },
  AGE,
];

export const BACKUP_TARGETS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'backupTargetURL',
    labelKey: 'longhorn.backupTarget.table.header.backupTargetURL',
    value: '$.spec.backupTargetURL',
    sort: ['$.spec.backupTargetURL'],
    search: '$.spec.backupTargetURL',
    dashIfEmpty: true,
  },
  {
    name: 'credentialSecret',
    labelKey: 'longhorn.backupTarget.table.header.credentialSecret',
    value: '$.spec.credentialSecret',
    sort: ['$.spec.credentialSecret'],
    search: '$.spec.credentialSecret',
    dashIfEmpty: true,
  },
  {
    name: 'pollInterval',
    labelKey: 'longhorn.backupTarget.table.header.pollInterval',
    value: '$.spec.pollInterval',
    sort: ['$.spec.pollInterval'],
    search: '$.spec.pollInterval',
    dashIfEmpty: true,
  },
  {
    name: 'lastSyncedAt',
    labelKey: 'longhorn.backupTarget.table.header.lastSyncedAt',
    value: '$.status.lastSyncedAt',
    sort: ['$.status.lastSyncedAt'],
    search: '$.status.lastSyncedAt',
    formatter: 'LiveDate',
  },
  AGE,
];

export const BACKUP_VOLUMES_HEADER = [
  STATE,
  {
    name: 'volumeName',
    label: 'Volume',
    value: 'volumeName',
    sort: ['volumeName'],
    search: 'volumeName',
    dashIfEmpty: true,
    formatter: 'BackupVolumeName',
  },
  {
    name: 'size',
    label: 'Size',
    value: 'size',
    sort: ['size'],
    search: 'size',
    formatter: 'Si',
  },
  {
    name: 'backupTargetName',
    label: 'Backup Target',
    value: 'backupTargetName',
    sort: ['backupTargetName'],
    search: 'backupTargetName',
    dashIfEmpty: true,
  },
  {
    name: 'lastBackupAt',
    label: 'Last Backup At',
    value: 'lastBackupAt',
    sort: ['lastBackupAt'],
    search: 'lastBackupAt',
    formatter: 'LiveDate',
  },
  {
    name: 'createdAt',
    label: 'Created At',
    value: 'status.createdAt',
    sort: ['status.createdAt'],
    search: 'status.createdAt',
    formatter: 'LiveDate',
  },
  {
    name: 'pvPvc',
    label: 'PV/PVC',
    value: 'kubernetesStatus',
    formatter: 'VolumePvPvc',
    align: 'center',
    width: 120,
  },
  {
    name: 'node',
    label: 'Workload/Pod',
    value: 'kubernetesStatus',
    formatter: 'VolumeNode',
  },
  AGE,
];

export const SYSTEM_BACKUPS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'version',
    labelKey: 'longhorn.systemBackup.table.header.version',
    value: '$.status.version',
    sort: ['$.status.version'],
    search: '$.status.version',
    dashIfEmpty: true,
  },
  {
    name: 'volumeBackupPolicy',
    label: 'Volume Backup Policy',
    value: '$.spec.volumeBackupPolicy',
    sort: ['$.spec.volumeBackupPolicy'],
    search: '$.spec.volumeBackupPolicy',
    dashIfEmpty: true,
  },
  AGE,
];

export const SYSTEM_RESTORE_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'version',
    labelKey: 'longhorn.systemRestore.table.header.version',
    value: 'version',
    sort: ['version'],
    search: 'version',
    dashIfEmpty: true,
  },
  AGE,
];

export const BACKING_IMAGES_HEADER = [
  STATE,
  {
    name: 'name',
    labelKey: 'longhorn.backingImage.table.header.name',
    sort: ['nameSort'],
    formatter: 'BackingImageName',
    canBeVariable: true,
    valueProp: 'nameDisplay',
  },
  {
    name: 'uuid',
    labelKey: 'longhorn.backingImage.table.header.uuid',
    value: '$.status.uuid',
    sort: ['$.status.uuid'],
    search: '$.status.uuid',
    dashIfEmpty: true,
    tooltip: '',
  },
  {
    name: 'actualSize',
    labelKey: 'longhorn.backingImage.table.header.actualSize',
    value: '$.status.size',
    sort: ['$.status.size'],
    search: '$.status.size',
    tooltip: "The physical storage space currently consumed by the image file on the host's file system",
    formatter: 'Si',
  },
  {
    name: 'virtualsize',
    labelKey: 'longhorn.backingImage.table.header.virtualSize',
    value: '$.status.virtualSize',
    sort: ['$.status.virtualSize'],
    search: '$.status.virtualSize',
    tooltip: 'The total logical capacity of the disk that the image represents',
    formatter: 'Si',
  },
  {
    name: 'sourcetype',
    labelKey: 'longhorn.backingImage.table.header.sourceType',
    value: '$.spec.sourceType',
    sort: ['$.spec.sourceType'],
    search: '$.spec.sourceType',
    dashIfEmpty: true,
  },
  {
    name: 'minNumberOfCopies',
    labelKey: 'longhorn.backingImage.table.header.minNumberOfCopies',
    value: '$.spec.minNumberOfCopies',
    sort: ['$.spec.minNumberOfCopies'],
    search: '$.spec.minNumberOfCopies',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'dataEngine',
    labelKey: 'longhorn.backingImage.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    search: '$.spec.dataEngine',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'nodeTags',
    labelKey: 'longhorn.backingImage.table.header.nodeTags',
    value: '$.spec.nodeSelector',
    formatter: 'Tag',
  },
  {
    name: 'diskTags',
    labelKey: 'longhorn.backingImage.table.header.diskTags',
    value: '$.spec.diskSelector',
    formatter: 'Tag',
  },
];

export const ENGINE_IMAGES_HEADER = [
  STATE,
  NAME_COL,
  IMAGE_NAME,
  {
    name: 'default',
    labelKey: 'longhorn.engineImage.table.header.default',
    value: 'isDefault',
    formatter: 'Checked',
    align: 'center',
  },
  {
    name: 'refCount',
    labelKey: 'longhorn.engineImage.table.header.refCount',
    value: '$.status.refCount',
    sort: ['$.status.refCount'],
    search: '$.status.refCount',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'buildDate',
    labelKey: 'longhorn.engineImage.table.header.buildDate',
    value: 'status.buildDate',
    formatterOpts: { addSuffix: true },
    formatter: 'LiveDate',
    sort: 'status.buildDate',
  },
];

export const INSTANCE_MANAGERS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'type',
    labelKey: 'longhorn.instanceManager.table.header.type',
    value: '$.spec.type',
    sort: ['$.spec.type'],
    search: '$.spec.type',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'data engine',
    labelKey: 'longhorn.instanceManager.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    search: '$.spec.dataEngine',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    name: 'node',
    labelKey: 'longhorn.instanceManager.table.header.node',
    value: '$.spec.nodeID',
    sort: ['$.spec.nodeID'],
    search: '$.spec.nodeID',
    formatter: 'NodeName',
  },
  {
    name: 'image',
    labelKey: 'longhorn.instanceManager.table.header.image',
    value: '$.spec.image',
    sort: ['$.spec.image'],
    search: '$.spec.image',
    dashIfEmpty: true,
  },
  AGE,
];

export const ORPHANS_HEADER = [
  STATE,
  {
    ...NAME_COL,
    width: 160,
    canBeVariable: false,
  },
  {
    name: 'node',
    labelKey: 'longhorn.orphans.table.header.node',
    value: '$.spec.nodeID',
    sort: ['$.spec.nodeID'],
    search: '$.spec.nodeID',
    formatter: 'NodeName',
  },
  {
    name: 'dataName',
    labelKey: 'longhorn.orphans.table.header.dataName',
    value: '$.spec.parameters.DataName',
    sort: ['$.spec.parameters.DataName'],
    search: '$.spec.parameters.DataName',
    dashIfEmpty: true,
  },
  {
    name: 'diskName',
    labelKey: 'longhorn.orphans.table.header.diskName',
    value: '$.spec.parameters.DiskName',
    sort: ['$.spec.parameters.DiskName'],
    search: '$.spec.parameters.DiskName',
    dashIfEmpty: true,
  },
  {
    name: 'diskPath',
    labelKey: 'longhorn.orphans.table.header.diskPath',
    value: '$.spec.parameters.DiskPath',
    sort: ['$.spec.parameters.DiskPath'],
    search: '$.spec.parameters.DiskPath',
    dashIfEmpty: true,
  },
  {
    name: 'instanceName',
    labelKey: 'longhorn.orphans.table.header.instanceName',
    value: '$.spec.parameters.InstanceName',
    sort: ['$.spec.parameters.InstanceName'],
    search: '$.spec.parameters.InstanceName',
    dashIfEmpty: true,
  },
  {
    name: 'instanceManager',
    labelKey: 'longhorn.orphans.table.header.instanceManager',
    value: '$.spec.parameters.InstanceManager',
    sort: ['$.spec.parameters.InstanceManager'],
    search: '$.spec.parameters.InstanceManager',
    dashIfEmpty: true,
  },
  {
    name: 'dataEngine',
    labelKey: 'longhorn.orphans.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    search: '$.spec.dataEngine',
    dashIfEmpty: true,
    align: 'center',
  },
  {
    ...AGE,
    width: 80,
  },
];

const ORPHAN_REPLICA_HIDDEN_COLUMNS = ['instanceName', 'instanceManager', 'dataEngine'];
const ORPHAN_INSTANCE_HIDDEN_COLUMNS = ['dataName', 'diskName', 'diskPath'];

export const ORPHANS_REPLICA_HEADER = ORPHANS_HEADER.filter(
  (header) => !ORPHAN_REPLICA_HIDDEN_COLUMNS.includes(header?.name)
);

export const ORPHANS_INSTANCE_HEADER = ORPHANS_HEADER.filter(
  (header) => !ORPHAN_INSTANCE_HIDDEN_COLUMNS.includes(header?.name)
);

export const BACKING_IMAGE_BACKUPS_HEADER = [
  STATE,
  {
    ...NAME_COL,
    labelKey: 'longhorn.backingImageBackup.table.header.backingImage',
    value: '$.spec.backingImage',
    getValue: (row: any) => row?.spec?.backingImage,
    sort: ['$.spec.backingImage'],
    search: '$.spec.backingImage',
    dashIfEmpty: true,
  },
  {
    name: 'backupName',
    labelKey: 'longhorn.backingImageBackup.table.header.backupName',
    value: '$.metadata.name',
    sort: ['$.metadata.name'],
    search: '$.metadata.name',
    dashIfEmpty: true,
  },
  {
    name: 'backupTarget',
    labelKey: 'longhorn.backingImageBackup.table.header.backupTarget',
    value: '$.spec.backupTargetName',
    sort: ['$.spec.backupTargetName'],
    search: '$.spec.backupTargetName',
    dashIfEmpty: true,
  },
  {
    name: 'size',
    labelKey: 'longhorn.backingImageBackup.table.header.size',
    value: '$.status.size',
    sort: ['$.status.size'],
    search: '$.status.size',
    formatter: 'Si',
  },
  {
    name: 'url',
    labelKey: 'longhorn.backingImageBackup.table.header.url',
    value: '$.status.url',
    sort: ['$.status.url'],
    search: '$.status.url',
    dashIfEmpty: true,
  },
  AGE,
];
